@startuml
hide circle
skinparam classAttributeIconSize 0

abstract "{abstract} \n Command" {
    {abstract} +execute()
}

class ChangeCommand {
    +execute()
}

class CheckCommand {
    +execute()
}

class ExitCommand {
    +execute()
}

class FlipCommand {
    +execute()
}

class HelpCommand {
    +execute()
}

class ResetCommand {
    +execute()
}

class Storage {
    +saveData(UserData)
}

class UserData {
   +balance : int
   +betAmount : int
   +winCount : int
   +loseCount : int
   +totalWon : int
   +totalLost : int
}

class AchievementList {
+update(UserData, Boolean)
+getPrintString() : String
}

"{abstract} \n Command" <|-- ChangeCommand
"{abstract} \n Command" <|-- CheckCommand
"{abstract} \n Command" <|-- ExitCommand
"{abstract} \n Command" <|-- FlipCommand
"{abstract} \n Command" <|-- HelpCommand
"{abstract} \n Command" <|-- ResetCommand

ChangeCommand --> UserData
ChangeCommand ..> Printer
ChangeCommand --> Storage

CheckCommand --> UserData
CheckCommand ..> Printer

FlipCommand --> UserData
FlipCommand --> AchievementList
FlipCommand --> Storage
FlipCommand ..> Printer

HelpCommand ..> Printer

ResetCommand --> Storage
ResetCommand --> UserData
ResetCommand ..> Printer

ExitCommand ..> Printer

@enduml
