@startuml
hide circle
skinparam classAttributeIconSize 0

class UserData {
   +currentWinStreak : int
   +currentLoseStreak : int
   +highestWinStreak : int
   +highestLoseStreak : int
   +winCount : int
   +loseCount : int
}

abstract "{abstract} \n Achievement" {
    {abstract} +update(UserData, Boolean)
}

class AchievementList {
    +update(UserData, Boolean)
}

class GamesAchievement {
    +update(UserData, Boolean)
}

class LoseStreakAchievement {
    +update(UserData, Boolean)
}

class WinCountAchievement {
    +update(UserData, Boolean)
}

class LoseCountAchievement {
    +update(UserData, Boolean)
}

class WinStreakAchievement {
    +update(UserData, Boolean)
}


GamesAchievement --|> "{abstract} \n Achievement"
LoseStreakAchievement --|> "{abstract} \n Achievement"
WinCountAchievement --|> "{abstract} \n Achievement"
WinStreakAchievement --|> "{abstract} \n Achievement"
LoseCountAchievement --|> "{abstract} \n Achievement"


AchievementList -- "{abstract} \n Achievement"
AchievementList ..> UserData
"{abstract} \n Achievement" ..> UserData

@enduml
